# Watch Me Code 2: Reading HTML tables from Websites

In [2]:
import pandas as pd

In [4]:
# HTTP Error - need to set a user agent
tables = pd.read_html("https://ist256.github.io")

HTTPError: HTTP Error 403: Forbidden

In [5]:
headers = {"User-Agent": "Mozilla/5.0"}
tables = pd.read_html("https://ist256.github.io", storage_options=headers)

2

In [8]:
tables[0].tail()

          Dates Topic (Click Link for Content and Assigned Readings)
11    4/1 - 4/7                                Lesson 10: Pandas I
12   4/8 - 4/14                               Lesson 11: Pandas II
13  4/15 - 4/21                      Lesson 12: Data Visualization
14  4/22 - 4/28                               Lesson 13: Web API’s
15   4/29 - 5/7                                   Complete Project

In [7]:
tables[1].sample(5)

,Date Due,Time Due,Gradebook,Points,Where,What is Due?
1,1/24/2024,11:59 PM,S01,3,Jupyterhub,01-Intro/SmallGroup-Intro.ipynb
4,1/31/2024,11:59 PM,S02,3,Jupyterhub,02-Variables/SmallGroup-Variables.ipynb
24,3/20/2024,11:59 PM,S08,3,Jupyterhub,08-Lists/SmallGroup-Lists.ipynb
10,2/14/2024,11:59 PM,S04,3,Jupyterhub,04-Iterations/SmallGroup-Iterations.ipynb
26,3/26/2024,11:59 PM,L09,3,Jupyterhub,09-Dictionaries/LAB-Dictionaries.ipynb

In [9]:
headers = {"User-Agent": "Mozilla/5.0"}
tables = pd.read_html("https://www.baseball-reference.com/leagues/MLB-standings.shtml", storage_options=headers)
len(tables)

6

In [10]:
from IPython.display import display
for index in range(len(tables)):
    print("INDEX:", index)
    display(tables[index])

INDEX: 0

                  Tm  W  L   W-L%   GB
0   New York Yankees  4  0  1.000   --
1  Baltimore Orioles  2  1  0.667  1.5
2     Boston Red Sox  2  2  0.500  2.0
3     Tampa Bay Rays  2  2  0.500  2.0
4  Toronto Blue Jays  2  2  0.500  2.0

INDEX: 1

                    Tm  W  L   W-L%   GB
0       Detroit Tigers  3  0  1.000   --
1  Cleveland Guardians  3  1  0.750  0.5
2      Minnesota Twins  2  1  0.667  1.0
3   Kansas City Royals  1  2  0.333  2.0
4    Chicago White Sox  0  3  0.000  3.0

INDEX: 2

                   Tm  W  L   W-L%   GB
0       Texas Rangers  2  1  0.667   --
1    Seattle Mariners  2  2  0.500  0.5
2  Los Angeles Angels  1  2  0.333  1.0
3   Oakland Athletics  1  3  0.250  1.5
4      Houston Astros  0  4  0.000  2.5

INDEX: 3

                      Tm  W  L   W-L%   GB
0         Atlanta Braves  2  1  0.667   --
1  Philadelphia Phillies  1  2  0.333  1.0
2   Washington Nationals  1  2  0.333  1.0
3          New York Mets  0  3  0.000  2.0
4          Miami Marlins  0  4  0.000  2.5

INDEX: 4

                    Tm  W  L   W-L%   GB
0   Pittsburgh Pirates  4  0  1.000   --
1    Milwaukee Brewers  3  0  1.000  0.5
2      Cincinnati Reds  2  1  0.667  1.5
3         Chicago Cubs  1  2  0.333  2.5
4  St. Louis Cardinals  1  3  0.250  3.0

INDEX: 5

                     Tm  W  L   W-L%   GB
0  Arizona Diamondbacks  3  1  0.750   --
1   Los Angeles Dodgers  4  2  0.667   --
2      San Diego Padres  3  3  0.500  1.0
3  San Francisco Giants  2  2  0.500  1.0
4      Colorado Rockies  1  3  0.250  2.0